### PR TITLE
[#1237] Align target with SimRel 2023-09

### PR DESCRIPTION
**Pull request by ruspl-afed**
Switch to notarized version of JNA

### CODE REVIEW

**Comment by ruspl-afed** [comment]
@merks do I need to do anything else with JNA to align with SimRel?

**Comment by merks** [comment]
> @merks do I need to do anything else with JNA to align with SimRel?

The direct from maven version is not currently causing Mac notarization problems but it has in the past.  Using the one with signed *.jnilib from https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/milestone/latest would be advisable.

**Review by eparovyshnaya — APPROVED** [review]
вот как...

**Comment by merks** [comment]
Thank you.  😃

**Comment by merks** [comment]
FYI,  you could consider to update your oshi dependency:

https://github.com/eclipse-orbit/orbit-simrel/blob/main/report/maven-osgi/passage/REPORT.md

**Comment by ruspl-afed** [comment]
Thank you Ed @merks , we will consider this dependency update if new version of oshi will work well for us

**Pull request merged**
