### PR TITLE
Import OSGi packages instead of requiring org.eclipse.osgi.*-bundles

### PR DESCRIPTION
**Pull request by HannesWell**
Instead of requiring `org.eclipse.osgi(.services)` bundles their packages should be imported, if necessary. The reasons are similar like the ones described in #1121. Furthermore `org.eclipse.osgi.services` is a bundle that will probably be removed in the future because it is replaced by the 'original' osgi-bundles from Maven-Central containing the code that used to be embedded in that plugin.

Importing the package `org.osgi.service.component.annotations` for Declarative-Service Annotations is also not necessary because recent PDE-DS and Tycho versions inject them to the classpath at compile-time already.

The only problem is that `org.eclipse.passage.lic.equinox` reexported `org.eclipse.osgi` and `org.eclipse.osgi.services`. The API-problems can be suppressed but down-stream consumers have to be adjusted, in case they reference classes from that bundle. Ideally they then import the required packages as well.

### CODE REVIEW

**Comment by HannesWell** [comment]
@ruspl-afed can you please review this PR.

**Review by ruspl-afed — COMMENTED** [review]
> org.osgi.service.event;version="[1.4.0,2.0.0)"

Do we really need to set upper bound here @HannesWell ?

**Comment by HannesWell** [comment]
> > org.osgi.service.event;version="[1.4.0,2.0.0)"
> 
> Do we really need to set upper bound here @HannesWell ?

It probably depends on if it is likely that there will be a version 2 or higher that breaks the current API and if you want to guard against wiring to it then. But I don't know if that is likely. I just added it for good SemVer/OSGi practice.
But if you prefer only a lower bound like `org.osgi.service.event;version="1.4.0"` I can change that.
Just let me know, what you prefer.

**Comment by ruspl-afed** [comment]
> and if you want to guard against wiring to it then

We would like Passage to keep working with future major versions of used libraries as long as possible, like [EMF](https://www.eclipse.org/modeling/emf/) does. 

> Just let me know, what you prefer.

In Passsage we prefer to omit version constraints _as far as possible_ , because
1) setting lower bound makes backporting harder
2) setting upper bound blocks the work for future versions

I don't deny SemVer/OSGi practices with keeping constraints, they are formally good. But following these restricitve practices implies endless support resources that is not the case in modern reality.

**Comment by HannesWell** [comment]
Yes stricter version ranges often require more adjustments that's right. But the intention is to make things fail fast already when building/installing an application instead of later at runtime with things like NoClassDefFoundError or the pendants for methods/fields.
But if you only use classes/methods/fields available in the very first version and are sure that non of the used elements is removed in the future that is unnecessary, yes.

I converted all version ranges to only lower-bounds of `"1.0.0"`.

**Review by ruspl-afed — APPROVED** [review]

**Comment by ruspl-afed** [comment]
Thank you @HannesWell

**Comment by HannesWell** [comment]
Thank you for reviewing.

**Pull request merged**
