### PR TITLE
Remove passage.lbc.target.feature from passage.lbc.execute.feature

### PR DESCRIPTION
**Pull request by HannesWell**
Fixes https://github.com/eclipse-passage/passage/issues/1123

### CODE REVIEW

**Review by ruspl-afed — APPROVED** [review]
Yes, we can remove this feature from the list of "requires". 
However, this fix does not look complete, perhaps `org.eclipse.passage.lbc.target.feature` feature is not needed at all.

**Comment by HannesWell** [comment]
> Yes, we can remove this feature from the list of "requires". However, this fix does not look complete, perhaps `org.eclipse.passage.lbc.target.feature` feature is not needed at all.

It is not unlikely that this feature is not required at all, especially if the included Plug-ins are already required by any one of Passage's plugins.
If you want I can create a PR to remove this target-feature.

**Comment by HannesWell** [comment]
> Yes, we can remove this feature from the list of "requires". However, this fix does not look complete, perhaps `org.eclipse.passage.lbc.target.feature` feature is not needed at all.

It looks like that feature is used in the `org.eclipse.passage.lbc.repository` to include passage dependencies. Therefore I think you should keep it to build that repo.

**Comment by ruspl-afed** [comment]
I know, and it is used also for FLS product definition. The question was a bit wider, but we can forget about it for a while.

**Comment by HannesWell** [comment]
> I know, and it is used also for FLS product definition. The question was a bit wider, but we can forget about it for a while.

You build the products with Tycho, don't you? Because Tycho/P2 installs all required dependencies automatically into the product, so that is actually not necessary. But the `passage.lbc.target.feature` is marked as root feature, so your intention is to allow updating of that plugin independently? Or is that just by chance?

**Comment by ruspl-afed** [comment]
> You build the products with Tycho, don't you?

we do.

> so your intention is to allow updating of that plugin independently? Or is that just by chance?

I think this feature was containing much more in the past and the intention was to allow upgrading this "target" independently.

**Pull request merged**
