### PR TITLE
[#1469] Prepare releng to start 4.1.0 development

### PR DESCRIPTION
**Pull request by zelenyhleb**
- incremented bundles manifest versions
- incremented features manifest versions
- incremented maven modules poms versions
- updated info for p2 site

### CODE REVIEW

**Comment by zelenyhleb** [comment]
Thank you @ruspl-afed for your notes. 

Just updated commit and PR message according to your request. Please re-review.

**Comment by ruspl-afed** [comment]
> maden 

one typo in PR description

**Comment by ruspl-afed** [comment]
Please don't forget to renew the formulation of original issue #1469

**Review by ruspl-afed — APPROVED** [review]
LGTM

**Comment by ruspl-afed** [comment]
Although test failure looks unrelated,  please create an issue regarding this test failure @zelenyhleb , it _may_ indicate a trouble we don't know about.
```
java.lang.ClassCastException: class org.bouncycastle.bcpg.TrustPacket cannot be cast to class org.bouncycastle.bcpg.UnknownPacket (org.bouncycastle.bcpg.TrustPacket and org.bouncycastle.bcpg.UnknownPacket are in unnamed module of loader org.eclipse.osgi.internal.loader.EquinoxClassLoader @291cbe70)
	at org.bouncycastle.openpgp.PGPObjectFactory.nextObject(Unknown Source)
	at org.bouncycastle.openpgp.PGPSecretKeyRingCollection.<init>(Unknown Source)
	at org.bouncycastle.openpgp.jcajce.JcaPGPSecretKeyRingCollection.<init>(Unknown Source)
	at org.eclipse.passage.lic.bc.BcResidentSecretKey.rings(BcResidentSecretKey.java:60)
```

**Pull request merged**
